name: Unit Test Coverage
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - build.gradle
      - gradle.properties
  pull_request:
    types: [opened, synchronize]
    paths:
      - src/**
      - build.gradle
      - gradle.properties
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        groovy: [ '2.4.21', '4.0.6']
        java: [ '11', '17' ]
        exclude:
          - groovy: '2.4.21'
            java: '17'
    name: Java ${{ matrix.java }} Groovy ${{ matrix.groovy }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - if: ${{ !(matrix.groovy == '4.0.6' && matrix.java == '17') }}
        name: Unit Tests
        run: GROOVY_VERSION=${{ matrix.groovy }} ./gradlew check
      - if: ${{ matrix.groovy == '4.0.6' && matrix.java == '17' }}
        name: Coveralls Test Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: GROOVY_VERSION=${{ matrix.groovy }} ./gradlew coveralls
      - if: ${{ matrix.groovy == '4.0.6' && matrix.java == '17' }}
        name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
